name: Hello Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Print Hello
      run: echo "Hello"

    - name: install-aws-cli
      uses: unfor19/install-aws-cli-action@v1
      with:
        version: 2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: upload the file from s3 bucket
      run: aws s3 cp ods.txt s3://odyssey-buc 

    - name: Send email notification
      uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com  # Change this to your SMTP server address
          server_port: 587  # Change this to your SMTP server port
          username: ${{ secrets.EMAIL_USERNAME }}  # Set your email username as a secret
          password: ${{ secrets.EMAIL_PASSWORD }}  # Set your email password as a secret
          subject: GitHub Actions Notification
          body: |
            Hello from GitHub Actions!
            This is a test email notification.
          to: nagarajubeee@gmail.com  # Set the recipient email address
          from: nagarajcapgemini@gmail.com  # Set the sender email address
 

   